GenCalculator af(7.2,9.0);
    // af.add();
    // GenCalculator sf(3.2,2.1);
    // sf.subtract();
    // GenCalculator mf(5.3,6.5);
    // mf.multiply();
    // GenCalculator df(10.25,2.3);
    // df.division();
    // GenCalculator as('A','B');
    // as.add();
    // GenCalculator ss('D','C');
    // ss.subtract();
    // GenCalculator ms('E','F');
    // ms.multiply();
    // GenCalculator ds('H','G');
    // ds.division();